### ISSUE TITLE
Cannot type polish characters "ó" (right alt+O) and "ł" (right alt+L)

### ISSUE THREAD

**Issue by radkoncy** [rebornix/vscode-vs-keybindings#10]
After installing this extension I can't type polish characters "ó" (right alt+O) and "ł" (right alt+L).
This is because of the new shortcuts:

package.json line 104:
            {
                "key": "ctrl+alt+o",
                "command": "workbench.action.output.toggleOutput"
            },
            {
                "key": "ctrl+alt+l",
                "command": "workbench.view.explorer"
            },

**Comment by taurit** [comment]
Here's a workaround for those who encounter this problem.

To make "ó" and "ł" work without removing this extension, go to `File->Preferences->Keyboard shortcuts` and remove two shortcuts listed by @radkoncy. This will actually add the following code to our custom `keybindings.json`:

```json
[
    {
        "key": "ctrl+alt+o",
        "command": "-workbench.action.output.toggleOutput"
    },
    {
        "key": "ctrl+alt+l",
        "command": "-workbench.view.explorer"
    }
]
```

**Comment by rebornix** [comment]
This issue was moved to Microsoft/vscode-vs-keybindings#10
