### ISSUE TITLE
This extension does not work as expected

### ISSUE THREAD

**Issue by pantonis** [rebornix/vscode-vs-keybindings#16]
I have downloaed this extension but It does not seem to work. eg. Ctrl E + ctrl D in vs 2017 formats the document. Here it's not working.

**Comment by drake7707** [comment]
I think only the General Settings from Visual Studio are supported. CTRL+E, CTRL+D is a keyboard shortcut from the Visual C# Settings

**Comment by rebornix** [comment]
This issue was moved to Microsoft/vscode-vs-keybindings#9
