### ISSUE TITLE
Shift-Alt-Down conflicts

### ISSUE THREAD

**Issue by alexandrudima** [rebornix/vscode-vs-keybindings#19]
Extracted from https://github.com/Microsoft/vscode/issues/29327#issuecomment-333005471

From @tohagan 

---

In VSCode 1.16.1 I found that there is a keyboard mapping conflict for Shift-Alt-Down:
 - Copy Line Down (wanted) 
 - cursorColumnSelectDown (not wanted)

Further I found that ALL the cursorColumnSelect* functions have multple keyboard mappings are creating more keyboard shortcut conflicts.

**Comment by tohagan** [comment]
- VSCode Version: 1.16.1
- OS Version: Win7 

Steps to Reproduce:

`Shift-Alt-Down` used to map to **Copy Line Down**. 
It's now overriden by a conflicting **cursorColumnSelectDown**

1. Open Keyboard Shortcuts.
2. Search for "Shift+Alt+DownArrow"
3. Displays the conflicted mapping to both **Copy Line Down**.  and **cursorColumnSelectDown**

4. Search for "cursorColumnSelect" prefix and you'll see all of these functions have multiple key mappings that I've confirmed are creating even more conflicts.

5. I Removed all cursorColumnSelect* keymappings that used Shift-Alt-* but retained the Ctrl-Shift-Alt-* mappings.

See also https://github.com/Microsoft/vscode/issues/29327

**Comment by rebornix** [comment]
This issue was moved to Microsoft/vscode-vs-keybindings#7
