### ISSUE TITLE
Anyone active here?

### ISSUE THREAD

**Issue by kirkone** [rebornix/vscode-vs-keybindings#23]
Hi,

I just wonder if there is anyone active maintaining this extension at the moment?
Can I offer some help?

I think this is a very valuable extension and there are many active users. So this should get some care.

I don't want to complain but liked to offer my help.

Greetings
KirK

**Comment by rebornix** [comment]
@kirkone I have been just back from my vacation ;) I'd love to see help from community, either by triaging issues or sending/reviewing PRs, thanks in advance!

**Comment by kirkone** [comment]
Hi,

welcome back 😄 
I will do my best to help out.
