### ISSUE TITLE
Ctrl+L doesn't quite work the same

### ISSUE THREAD

**Issue by mlimber** [rebornix/vscode-vs-keybindings#3]
Hi, thanks for this extension. I note that Ctrl+L doesn't do quite the same thing as on Visual Studio. There, with nothing selected, it cuts the current line with cr-lf and moves the cursor to the start of the line, and with text selected it it acts like Ctrl+X. I only use it with no selection.

My understanding (drawing on this [vscode feature request](https://github.com/Microsoft/vscode/issues/171)) is that one would need to define a new command in the extension to call other commands conditionally.

**Comment by waderyan** [comment]
@rebornix have you looked into this at all? This might be a good candidate to add.
