### ISSUE TITLE
ctrl+up and ctrl+down

### ISSUE THREAD

**Issue by alexdima** [rebornix/vscode-vs-keybindings#33]
See https://github.com/Microsoft/vscode/issues/47487 which claims that in Visual Studio the cursor is kept visible when using ctrl+up and ctrl+down. This can be achieved via the keybindings:

```
    {
        "key": "ctrl+down",
        "command": "editorScroll",
        "args": {
            "to": "down",
            "by": "line",
            "revealCursor": true
        }
    },
    {
        "key": "ctrl+up",
        "command": "editorScroll",
        "args": {
            "to": "up",
            "by": "line",
            "revealCursor": true
        }
    }
```

**Comment by alexdima** [comment]
ping @rebornix -- we are still getting issues in vscode about this. It might help if the keymap would have these in to make ctrl+up / ctrl+down more similar to Visual Studio.

**Comment by rebornix** [comment]
@alexdima thanks! I'll publish a new version with your proposed change.
