### ISSUE TITLE
Ctrl+space is not deleteWordStartLeft

### ISSUE THREAD

**Issue by giggio** [rebornix/vscode-vs-keybindings#4]
`ctrl+space` in VS is a shortcut to Intellisense, or as VSCode calls it, `triggerSuggest`. Why is this extension remapping it to deleteWordStartLeft?

**Comment by giggio** [comment]
Cool, it is fixed. When is the release happening?

**Comment by waderyan** [comment]
I should have time later today... latest tomorrow morning.
