### ISSUE TITLE
Can you also provide invert of this mapping?

### ISSUE THREAD

**Issue by VishmayShah** [rebornix/vscode-vs-keybindings#47]
Can you also provide invert of this mapping? 
I'm looking for Visual Studio Code Keymap for Visual Studio.

Some of VS code shortcuts are great like Alt+ ← / → Go back / forward.

**Comment by ronwarner** [comment]
I could be wrong, but I think this exists already in Visual Studio 2019, and maybe earlier versions.  Try Tools >> Options >> Environment >> Keyboard and then see if "Visual Studio Code" is one of the mapping schemes available in the dropdown.

**Comment by VishmayShah** [comment]
@ronwarner 
It worked!
Thanks
