### ISSUE TITLE
I tried to install the Visual Studio Keymap but I don't think it worked.

### ISSUE THREAD

**Issue by bvpmiranda** [rebornix/vscode-vs-keybindings#6]
I tried to install the Visual Studio Keymap expecting to get the same shortcuts as I'm used on Visual Studio 2015.

I don't know if I did something wrong but it's been really hard for me using the editor and learning all over again the shortcuts. 

I now I can remap them but to remember them all is a pain in the neck.

If this extensions is not for that. Does anybody have already mapped the shortcuts to be similar to the ones from VS2015?

Thanks

**Comment by waderyan** [comment]
Hi @bvpmiranda - the list of keybindings are here. https://github.com/rebornix/vscode-vs-keybindings/blob/master/package.json#L26

Which ones are working for you?

**Comment by bvpmiranda** [comment]
Apparently the bindings are still the default ones. Like, to fold everything on VS2015 I use ctrl+M ctrl+L.
In VSCode it's ctrl+k ctrl+0.

When I installed the extension, I thought It'd change to ctrl+M ctrl+L.

**Comment by waderyan** [comment]
This extension is in preview phase knowing that we missed some. Can you open a PR and add that keybinding?

**Comment by rebornix** [comment]
@bvpmiranda I've fixed the fold all issue. It would be really awesome if you can point out what other keybindings are bothering you, they should be easy to add if the command it's already there in Code.

@waderyan I've bumped the version. Feel free to have a new release.
