### ISSUE TITLE
The addSelectionToNextFindMatch shortcut overwrites the default closeEditor

### ISSUE THREAD

**Issue by ventsislav-georgiev** [rebornix/vscode-vs-keybindings#9]
The `closeEditor` and `closeWindow` shortcuts are bound to `ctrl+w` and they do not work after installation of the extension.

**Comment by waderyan** [comment]
Hi, unfortunately with a keymap that is the case. VS binds ctrl+w to a different. I added a new keybinding (ctrl+f4) which now maps to`closeActiveEditor`
